# Continuous Deployment Pipeline Build Configuration for branch: */master

###########################################################
# BUILD CONFIGURATION
###########################################################
build:
  git.branch: "*/master"
  slave.node: "dev-perl-nap-xt"
  jdk.version: "JDK1.7"
  artefact.type: "package"

###########################################################
# TEST CONFIGURATION
###########################################################
test:
  unit.enabled: false
  regression.enabled: false
  coverage.enabled: false
  load.enabled: false

###########################################################
# NOTIFICATION CONFIGURATION
###########################################################
notify:
  email: "bernard.gould@net-a-porter.com"
  sonar.enabled: false


