###########################################################
# BUILD CONFIGURATION
###########################################################
build:
  git.branch: "*/master"
  slave.node: "xbuild"
  jdk.version: "JDK1.8"
  artefact.type: "package"

###########################################################
# TEST CONFIGURATION
###########################################################
test:
  unit.enabled: true
  regression.enabled: false
  coverage.enabled: false
  load.enabled: false

###########################################################
# NOTIFICATION CONFIGURATION
###########################################################
notify:
  email: "fulfilmentdash@net-a-porter.com"
  sonar.enabled: false